---
name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.0-alpha.6'

      - name: Run tests
        run: |
          pip install -r requirements/dev.txt
          coverage run --source=. -m pytest

      - name: Generate coverage badge
        if: github.ref == 'refs/heads/master'
        run: |
          coverage-badge -o /tmp/badge.svg

      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Upload coverage badge to S3
        if: github.ref == 'refs/heads/master'
        run: |
          aws s3 cp /tmp/badge.svg s3://puroboros/badge.svg
